language: go
sudo: false
go:
  - 1.5
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - go get github.com/smartystreets/goconvey/convey
script:
  - go test -v
  - "$HOME/gopath/bin/goveralls -service=travis-ci"
